server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/clientes/**

        - id: reserva-service
          uri: lb://reserva-service
          predicates:
            - Path=/api/reservas/**

        - id: descuentoFrecuente-service
          uri: lb://descuentoFrecuente-service
          predicates:
            - Path=/api/descuento-frecuencia/**

        - id: descuentoPorCantidad-service
          uri: lb://descuentoPorCantidad-service
          predicates:
            - Path=/api/descuento-personas/**

        - id: karts-service
          uri: lb://karts-service
          predicates:
            - Path=/api/karts/**

        - id: rack-service
          uri: lb://rack-service
          predicates:
            - Path=/api/rack-semanal/**

        - id: reporte-service
          uri: lb://reporte-service
          predicates:
            - Path=/api/reportes/**

        - id: tarifaEsp-service
          uri: lb://tarifaEsp-service
          predicates:
            - Path=/api/tarifa-especial/**

        - id: tarifa-service
          uri: lb://tarifa-service
          predicates:
            - Path=/api/tarifas/**
